### ISSUE TITLE
issues with provided xnnpack build

### ISSUE THREAD

**Issue by ThomAce** [vitoplantamura/OnnxStream#16]
Hi,
I have a build issue on Raspberry Pi4 with XNNPACK building, despite I followed the attached guidance. 

These error messages appeared. Wondering if anybody else faced with the same...

`/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:` In function ‘cpuinfo_arm64_linux_decode_isa_from_proc_cpuinfo’:
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:14:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_AES’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_AES’?
   14 |  if (features & CPUINFO_ARM_LINUX_FEATURE_AES) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE2_AES
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:14:17: note: each undeclared identifier is reported only once for each function it appears in
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:17:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_PMULL’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_PMULL’?
   17 |  if (features & CPUINFO_ARM_LINUX_FEATURE_PMULL) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE2_PMULL
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:20:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_SHA1’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_SHA1’?
   20 |  if (features & CPUINFO_ARM_LINUX_FEATURE_SHA1) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE2_SHA1
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:23:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_SHA2’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_SHA2’?
   23 |  if (features & CPUINFO_ARM_LINUX_FEATURE_SHA2) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE2_SHA2
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:26:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_CRC32’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_CRC32’?
   26 |  if (features & CPUINFO_ARM_LINUX_FEATURE_CRC32) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE2_CRC32
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:29:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_ATOMICS’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_TLS’?
   29 |  if (features & CPUINFO_ARM_LINUX_FEATURE_ATOMICS) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE_TLS
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:30:6: error: ‘struct cpuinfo_arm_isa’ has no member named ‘atomics’
   30 |   isa->atomics = true;
      |      ^~
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:51:35: error: ‘CPUINFO_ARM_LINUX_FEATURE_FPHP’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_FPA’?
   51 |   const uint32_t fp16arith_mask = CPUINFO_ARM_LINUX_FEATURE_FPHP | CPUINFO_ARM_LINUX_FEATURE_ASIMDHP;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                   CPUINFO_ARM_LINUX_FEATURE_FPA
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:51:68: error: ‘CPUINFO_ARM_LINUX_FEATURE_ASIMDHP’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_EDSP’?
   51 |  uint32_t fp16arith_mask = CPUINFO_ARM_LINUX_FEATURE_FPHP | CPUINFO_ARM_LINUX_FEATURE_ASIMDHP;
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                             CPUINFO_ARM_LINUX_FEATURE_EDSP
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:80:20: error: ‘CPUINFO_ARM_LINUX_FEATURE_ASIMDRDM’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_IDIVT’?
   80 |     if (features & CPUINFO_ARM_LINUX_FEATURE_ASIMDRDM) {
      |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                    CPUINFO_ARM_LINUX_FEATURE_IDIVT
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:86:18: error: ‘CPUINFO_ARM_LINUX_FEATURE2_I8MM’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_IWMMXT’?
   86 |  if (features2 & CPUINFO_ARM_LINUX_FEATURE2_I8MM) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  CPUINFO_ARM_LINUX_FEATURE_IWMMXT
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:87:6: error: ‘struct cpuinfo_arm_isa’ has no member named ‘i8mm’
   87 |   isa->i8mm = true;
      |      ^~
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:117:19: error: ‘CPUINFO_ARM_LINUX_FEATURE_ASIMDDP’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_EDSP’?
  117 |    if (features & CPUINFO_ARM_LINUX_FEATURE_ASIMDDP) {
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   CPUINFO_ARM_LINUX_FEATURE_EDSP
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:122:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_JSCVT’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_IDIVT’?
  122 |  if (features & CPUINFO_ARM_LINUX_FEATURE_JSCVT) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE_IDIVT
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:128:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_FCMA’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_FPA’?
  128 |  if (features & CPUINFO_ARM_LINUX_FEATURE_FCMA) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE_FPA
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:131:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_SVE’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_SWP’?
  131 |  if (features & CPUINFO_ARM_LINUX_FEATURE_SVE) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE_SWP
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:132:6: error: ‘struct cpuinfo_arm_isa’ has no member named ‘sve’
  132 |   isa->sve = true;
      |      ^~
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:134:18: error: ‘CPUINFO_ARM_LINUX_FEATURE2_SVE2’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_SHA2’?
  134 |  if (features2 & CPUINFO_ARM_LINUX_FEATURE2_SVE2) {
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                  CPUINFO_ARM_LINUX_FEATURE2_SHA2
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:135:6: error: ‘struct cpuinfo_arm_isa’ has no member named ‘sve2’
  135 |   isa->sve2 = true;
      |      ^~
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:139:19: error: ‘CPUINFO_ARM_LINUX_FEATURE2_BF16’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_FPA’?
  139 |  if (features2 & (CPUINFO_ARM_LINUX_FEATURE2_BF16 | CPUINFO_ARM_LINUX_FEATURE2_SVEBF16)) {
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   CPUINFO_ARM_LINUX_FEATURE_FPA
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:139:53: error: ‘CPUINFO_ARM_LINUX_FEATURE2_SVEBF16’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE2_SHA1’?
  139 |  if (features2 & (CPUINFO_ARM_LINUX_FEATURE2_BF16 | CPUINFO_ARM_LINUX_FEATURE2_SVEBF16)) {
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                     CPUINFO_ARM_LINUX_FEATURE2_SHA1
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:140:6: error: ‘struct cpuinfo_arm_isa’ has no member named ‘bf16’
  140 |   isa->bf16 = true;
      |      ^~
/home/thomace/XNNPACK/build/cpuinfo-source/src/arm/linux/aarch64-isa.c:142:17: error: ‘CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM’ undeclared (first use in this function); did you mean ‘CPUINFO_ARM_LINUX_FEATURE_IDIVT’?
  142 |  if (features & CPUINFO_ARM_LINUX_FEATURE_ASIMDFHM) {
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                 CPUINFO_ARM_LINUX_FEATURE_IDIVT
gmake[2]: *** [cpuinfo/CMakeFiles/cpuinfo.dir/build.make:238: cpuinfo/CMakeFiles/cpuinfo.dir/src/arm/linux/aarch64-isa.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:880: cpuinfo/CMakeFiles/cpuinfo.dir/all] Error 2
gmake: *** [Makefile:149: all] Error 2

**Comment by vitoplantamura** [comment]
hi,

Very weird...

Try checking the compiler used by CMake: open the CMakeCache.txt file in
the build directory, locate the CMAKE_CXX_COMPILER variable, make note of
the path, and then run '<this path> --version.'

Thanks, Vito

**Comment by caofx0418** [comment]
your g++ version is too lower!  Upgrade it.

**Comment by ThomAce** [comment]
G++ version is 10.2.1. I don't believe that it is too old. the OS is up to date as well from bullseye/main.

**Comment by ThomAce** [comment]
Thank Vito,

It is the following:


/usr/bin/c++ --version
c++ (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by vitoplantamura** [comment]
yes, it's the same version as my RPI.

Could you try deleting the "build" directory and rerunning the two "cmake"
commands?

Thanks, Vito

**Comment by ThomAce** [comment]
Tried everything, but at the same point it fails. cpuinfo/CMakeFiles/cpuinfo.dir/src/arm/linux/aarch64-isa.c.o

**Comment by ThomAce** [comment]
The previous issue fixed with different steps.

1.- cloned
2.- cd XNNPACK
3.- sudo ./scripts/build-linux-armhf.sh -DXNNPACK_ENABLE_ARM_DOTPROD=OFF

Everything built up properly. However, when I tried to build the OnnxStream, the following error came up:

OnnxStream/src/../../XNNPACK/include/xnnpack.h:15:10: fatal error: pthreadpool.h: No such file or directory
   15 | #include <pthreadpool.h>
      |          ^~~~~~~~~~~~~~~

**Comment by ThomAce** [comment]
git clone https://github.com/google/XNNPACK.git
cd XNNPACK
git rev-list -n 1 --before="2023-06-27 00:00" master
git checkout <COMMIT_ID_FROM_THE_PREVIOUS_COMMAND>
mkdir build
cd build
sudo ./scripts/build-linux-armhf.sh -DXNNPACK_ENABLE_ARM_DOTPROD=OFF -DYNNPACK_BUILD_TESTS=OFF -DXNNPACK_BUILD_BENCHMARKS=OFF
move created /linux/armhf files to ../../

download https://github.com/pytorch/pytorch/blob/main/caffe2/utils/threadpool/pthreadpool.h
Copy it to XNNPACK/include if not there...

git clone https://github.com/vitoplantamura/OnnxStream.git
cd OnnxStream
cd src
Copy pthreadpool.h to this folder
cmake -DMAX_SPEED=ON -DXNNPACK_DIR=dir path of XNNPACK
cmake --build . --config Release


Last message: [100%] Built target sd

It seems it worked. At least until this step.

**Comment by vitoplantamura** [comment]
hi,

which operating system are you using and for which architecture (32 or 64
bit)?

Thanks, Vito

**Comment by ThomAce** [comment]
Hi,

I'm having 64 bit. 

```
uname -m
aarch64
```

It seems with this workaround the stable diffusion built well. The next thing is to figure out how to use it properly because it misses some model files, etc... But, I haven't found any proper guidance for these step-by-step actions.

**Comment by vitoplantamura** [comment]
hi,

simply download the weights here:
https://github.com/vitoplantamura/OnnxStream/releases/tag/v0.1

I just tried to build XnnPack on my RPI 4 (4GB) with Ubuntu 22.04 64 bit,
and it builds correctly, without changes from the instructions in the main
README. There is something in your configuration that is preventing a
normal build, but it's not clear what it is.

Thanks, Vito

**Comment by ThomAce** [comment]
Hi,

Thank you very much. Yes, it is really weird. I'm using official Raspberry Pi OS from official source, everything up-to-date, nothing customized further. I trited to hunting down the root cause but without success. Glad that the build finally succeeded. Now, I'm going to download the package and will see if it is really really working. If not, I'm afraid of that I need to reinstall the whole Raspberry Pi OS. 

Thank you again for your kind support!

**Comment by ThomAce** [comment]
#656) Add (Add_847)
#657) Mul (Mul_849)
#658) Sigmoid (Sigmoid_850)
#659) Mul (Mul_851)
#660) MatMul (MatMul_852)
#661) Add (Add_853)
#662) Add (Add_854)
#663) ReduceMean (ReduceMean_855)
#664) Sub (Sub_856)
#665) Pow (Pow_858)
#666) ReduceMean (ReduceMean_859)
#667) Add (Add_861)
#668) Sqrt (Sqrt_862)
#669) Div (Div_863)
#670) Mul (Mul_864)
#671) Add (Add_865)
----------------[diffusion]---------------
step:0		#0) Unsqueeze (/time_proj/Unsqueeze)
#1) Mul (/time_proj/Mul)
=== ERROR === failed to create multiply operation

**Comment by vitoplantamura** [comment]
Please specify the "--rpi" command line argument.

Vito
