### ISSUE TITLE
vocab.txt

### ISSUE THREAD

**Issue by anhu** [vitoplantamura/OnnxStream#17]
Not sure how I should execute sd.  Just tried below. 
Couldn't find vocab.txt in anything that I brought down via git.
Not sure what I did wrong.  

Warm regards, Anthony

```
./sd --rpi 
----------------[start]------------------
positive_prompt: a photo of an astronaut riding a horse on mars
negative_prompt: ugly, blurry
output_png_path: ./result.png
steps: 10
----------------[prompt]------------------
=== ERROR === unable to open file: ./tokenizer/vocab.txt
```

**Comment by vitoplantamura** [comment]
hi,

the weights can be downloaded here:
https://github.com/vitoplantamura/OnnxStream/releases/tag/v0.1

Vito

**Comment by anhu** [comment]
Thank you so much.  It runs, but oddly, just gives snow.  :) no worries.  I will keep experimenting. Thank you so much!!
