### ISSUE TITLE
Things I want to ask

### ISSUE THREAD

**Issue by shashankx86** [vitoplantamura/OnnxStream#21]
can I run it on intel cpus??

OS: Debian GNU/Linux 12 (bookworm) x86_64 
Kernel: 6.1.0-12-amd64 
Uptime: 16 hours, 6 mins 
CPU: Intel i3-8130U (4) @ 3.400GHz 
GPU: Intel UHD Graphics 620 
Memory: 7851MiB 

If yes, How much time it may take while generating
and can i use it with auto1111?

**Comment by vitoplantamura** [comment]
hi,

of course you can use it on Intel cpus :-)

I looked at your CPU specs: it should take an hour and a half to generate
an image (10 steps). Use the "--not-tiled" option.

I often use A1111 (in Google Colab) but I'm not familiar enough with its
implementation to answer your question (but I think the answer is no).

Vito

**Comment by shashankx86** [comment]
thnx
