### ISSUE TITLE
Unable to run cmake

### ISSUE THREAD

**Issue by ganesh3** [vitoplantamura/OnnxStream#26]
Hi,

I am following your instruction on README to set up the code on Ubuntu 2022 using WSL. I am getting the below error. Can you please help?

**/XNNPACK/OnnxStream/src/build# cmake -DMAX_SPEED=ON -DXNNPACK_DIR=/root/XNNPACK/
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.**

_CMake Error: The source directory "/root/XNNPACK/OnnxStream/src/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI._

**~/XNNPACK/OnnxStream/src/build# cmake --build . --config Release
Error: could not load cache**

Warm Regards
Ganesh

**Comment by vitoplantamura** [comment]
hi,

you forgot the two periods (..) at the end of the command.

Vito

**Comment by ganesh3** [comment]
command ran successfully
