### ISSUE TITLE
=== ERROR === read_file: unable to open file errors...

### ISSUE THREAD

**Issue by nich2408** [vitoplantamura/OnnxStream#31]
Just built the project on my raspberry pi 3b+, but everytime I launch it I get "unable to open file" error.

First I tried:
`./sd --models-path /home/pi/ai-projects/stable_diffusion_models_onnxstream/ --rpi`
where `/home/pi/ai-projects/stable_diffusion_models_onnxstream/` is a directory created by myself in which I put the .rar downloaded from github Releases page (win-x64-with-weights) 
but it gave me:
`=== ERROR === unable to open file: ./tokenizer/vocab.txt` like #20 

So i created tokenizer directory and copied the vocab.txt from the models directory but then it gave me:
`=== ERROR === read_file: unable to open file (./text_encoder_fp32/model.txt).`

Am I doing something wrong? Does the models directory have some strict requirements?

Thanks

**Comment by vitoplantamura** [comment]
hi,

you should simply unzip the rar file :-)

Vito

**Comment by nich2408** [comment]
I already unzipped it but nothing, I used unrar package (Ubuntu). Sorry If I didnt make it clear

**Comment by jaydenchan1027** [comment]
> hi, you should simply unzip the rar file :-) Vito

Where is the rar file

**Comment by vitoplantamura** [comment]
here:
https://github.com/vitoplantamura/OnnxStream/releases/download/v0.1/StableDiffusion-OnnxStream-Windows-x64-with-weights.rar

Vito

**Comment by nich2408** [comment]
Ok solved, to unrar it on Ubuntu i had to use unrar - x - r which keeps the folder structure.
Thanks for the help Vito, this project is great and the guide is clear
