### ISSUE TITLE
"failed to create multiply operation"

### ISSUE THREAD

**Issue by Pythonic456** [vitoplantamura/OnnxStream#4]
Built and running on Ubuntu 22.04, Intel Core i3 CPU M 330 @ 2.13GHz with 8GB of RAM.
Instructions followed exactly, and when it didn't work, I cleaned up and tried fresh again, still no luck.

```
$ ./sd --models-path SD/ --steps 3
----------------[start]------------------
positive_prompt: a photo of an astronaut riding a horse on mars
negative_prompt: ugly, blurry
output_png_path: ./result.png
steps: 3
----------------[prompt]------------------
----------------[diffusion]---------------
step:0          === ERROR === failed to create multiply operation
$
```

**Comment by vitoplantamura** [comment]
hi,

your CPU has only SSE support and should not support FP16 arithmetic.

Can you do a test passing --rpi as a command line argument?

thanks, Vito

**Comment by Pythonic456** [comment]
That seems to have fixed the issue, which was no support for FP16 arithmetic, thank you.
It's taking about 10 minutes per step, is this normal, and are there any performance boosts I may be able to apply?

**Comment by vitoplantamura** [comment]
No, unfortunately there is currently no way to speed up the process. There
are a number of optimizations that could be made to the code, which I hope
to develop and release in the future.

Vito

**Comment by Pythonic456** [comment]
Alright, thank you.
Any possible way to run the model as image2image?

**Comment by vitoplantamura** [comment]
I have no plans to support img2img at the moment. The main purpose of
OnnxStream is to demonstrate that it is possible to run large transformer
models on devices with very little RAM, such as the RPI Zero 2,

Vito

**Comment by Pythonic456** [comment]
Ok, thank you :)
