### ISSUE TITLE
[question] your Mistral-to-ONNX export script

### ISSUE THREAD

**Issue by idruker-cerence** [vitoplantamura/OnnxStream#53]
Here is how a dummy input data is prepared in the script:

    dummy_input = (torch.tensor([[1, 2, 3]], dtype=torch.int64), # input_ids
                  torch.tensor([[1, 1, 1, 1, 1, 1]], dtype=torch.int64),   # attention_mask
                  torch.tensor([[3, 4, 5]], dtype=torch.int64))              #position_ids

I wonder 
1) why is attention_mask of size 6? Should not it be of the same size as input_ids'?
2) why does position_ids point to position 3, 4, and 5 while there are only input_ids elements# 0, 1, 2?

Thank you

**Comment by vitoplantamura** [comment]
hi,

This is how you can leverage KV caching in the LlamaForCausalLM class, to greatly speed up inference.

In the specific case of your example, you are telling the model that the entire sequence length is 6, that the new tokens are [1,2,3] and that they have position [3,4,5].

The various parameters are explained in the original python source code (https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py).

Vito

**Comment by idruker-cerence** [comment]
Thank you!

**Comment by idruker-cerence** [comment]
Thank you!
