### ISSUE TITLE
Tensor memory layout

### ISSUE THREAD

**Issue by thexa4** [vitoplantamura/OnnxStream#61]
To run a finetuned SD1.5 model I seem to need support for the [Flatten](https://onnx.ai/onnx/operators/onnx__Flatten.html#flatten-13) operator. I have the following line in model.txt that I want to support:

```
/text_model/Flatten:Flatten*input:last_5F_hidden_5F_state(1,77,768)*output:_2F_text_5F_model_2F_Flatten_5F_output_5F_0(77,768)*axis:2
```

I managed to add support for parsing the line [here](https://github.com/vitoplantamura/OnnxStream/blob/d0975d6d815f6ffe16c04706cb5ba4d19ac37bb5/src/onnxstream.cpp#L4152) but I don't know to get values from a Tensor at a specific coordinate. Is there a way to fetch and set a value given a coordinate?

For reference, this is my code so far
```c++
        else if (op.m_type == "Flatten")
        {
            if (op.m_input.size() != 1) throw std::invalid_argument(op.m_type + ": wrong number of inputs.");
            if (op.m_output.size() != 1) throw std::invalid_argument(op.m_type + ": wrong number of outputs.");

            int axis = 1;

            for (auto& a : op.m_attributes)
                if (a.first == "axis")
                    axis = std::stoi(a.second);
                else
                    throw std::invalid_argument(op.m_type + ": unrecognized attribute: " + a.first + ".");

            if (axis < 0)
                throw std::invalid_argument(op.m_type + ": axis must be positive (not implemented).");

            auto& data = get_tensor_data(op.m_input[0], true /* make_copy */);
            auto& output = op.m_output[0];

            int dim1 = 1;
            int dim2 = 1;
            int axisLeft = axis;
            for (auto& d : data.m_shape) {
                if (axisLeft > 0) {
                    dim1 *= d;
                    axisLeft--;
                } else {
                    dim2 *= d;
                }
            }

            std::vector<size_t> output_shape;
            output_shape.push_back(dim1);
            output_shape.push_back(dim2);

            if (!check_output_shape(output_shape, output.m_shape))
                throw std::invalid_argument(op.m_type + ": unexpected shape of output.");

            throw std::invalid_argument(op.m_type + ": not fully implemented.");
        } else ...
```

**Comment by vitoplantamura** [comment]
hi,

there are no helper methods for manipulating the contents of a Tensor.

In this case, I think the simplest solution is to replace this operator
with a Squeeze or a Reshape, directly in the txt file.

The Squeeze takes two parameters: the first is the input tensor, the second
is the index of the dimension to remove in int64 format, in this case 0.

The second parameter should be the name of a new, newly created file, with
4 bytes set to zero in it.

Vito

**Comment by thexa4** [comment]
Thanks, that worked! If someone else runs into this, this script can patch up the model.txt:

```bash
dd if=/dev/zero bs=1 count=8 of=output/text_encoder_fp32/squeeze_index.bin
sed -i -E 's@/([^/]+)/([^:]+):Flatten\*input:([^*]+)\*output:([^*]+)\*.*@/\1/\2:Squeeze*input:\3;squeeze_index.bin(int64:1)*output:\4@' output/text_encoder_fp32/model.txt
```

**Comment by thexa4** [comment]
It manages to run the model with this change but unfortunately all models I converted this way result in a black picture. The latent file also seems very repetitive (maybe all zeroes?)

I haven't been able to find any finetuned model that does not use the `Flatten`. Only the base model seems to convert correctly and produce images.

**Comment by vitoplantamura** [comment]
Are these finetuned models on HF?

Could you pass me the link to one of these so I can take a look?

Vito

**Comment by thexa4** [comment]
I've managed to reproduce the issue with a non-modified checkpoint: [v1-5-pruned.safetensors](https://huggingface.co/runwayml/stable-diffusion-v1-5/blob/39593d5650112b4cc580433f6b0435385882d819/v1-5-pruned.safetensors) (currently on main as of writing)

This is the [converted model](https://warc.maxmaton.nl/picasso/2024-05-14/model.tar.gz) that is runnable by the sd executable. I've tested with the version in [this commit](https://github.com/vitoplantamura/OnnxStream/commit/0c6178717e512be111d6d33989e5c681487a614a). (latest on master as of writing)

Only text encoder and unet have been converted, rest is from the original windows zip. Conversion was done as follows:

```bash
# convert ckpt to onnx
python3 convert_stable_diffusion_checkpoint_to_onnx.py --model_path "v1-5-pruned.safetensors" --output_path ./output/raw --opset 14

# simplify unet
python3 ./onnxsim_large_model/simplify_large_onnx.py -m output/raw/unet/model.onnx -o output/simple/unet.onnx

# simplify text_encoder
python3 -m onnxsim --overwrite-input-shape="onnx::Reshape_0:1,77" output/raw/text_encoder/model.onnx output/simple/text_encoder.onnx

# convert unet to sd format
python3 onnx2txt.py output/simple/unet.onnx output/unet_fp16 fp16

# convert text_encoder to sd format
python3 onnx2txt.py output/simple/text_encoder.onnx output/text_encoder_fp32 fp32
dd if=/dev/zero bs=1 count=8 of=output/text_encoder_fp32/squeeze_index.bin
sed -i -E 's@/([^/]+)/([^:]+):Flatten\*input:([^*]+)\*output:([^*]+)\*.*@/\1/\2:Squeeze*input:\3;squeeze_index.bin(int64:1)*output:\4@' output/text_encoder_fp32/model.txt

mv output/text_encoder_fp32 model/
mv output/unet_fp16 model/
```

The following files are available in case you want to inspect the conversion process:
 - [v1-5-pruned.safetensors](https://warc.maxmaton.nl/picasso/2024-05-14/v1-5-pruned.safetensors): File I used to do the conversion. [sha256sum: 1a189f0be69d6106a48548e7626207dddd7042a418dbf372cefd05e0cdba61b6]
 - [raw.tar.gz](https://warc.maxmaton.nl/picasso/2024-05-14/raw.tar.gz): Output of conversion from ckpt to onnx
 - [simple.tar.gz](https://warc.maxmaton.nl/picasso/2024-05-14/simple.tar.gz): Output of simplification
 - [convert_stable_diffusion_checkpoint_to_onnx.py](https://warc.maxmaton.nl/picasso/2024-05-14/convert_stable_diffusion_checkpoint_to_onnx.py): Python script to do conversion from ckpt to onnx
 - [simplify_large_onnx.py](https://warc.maxmaton.nl/picasso/2024-05-14/simplify_large_onnx.py): Simplifier for larger onnx models
 - [onnx2txt.py](https://warc.maxmaton.nl/picasso/2024-05-14/onnx2txt.py): Python script to convert onnx to sd format


List of package versions: (running on `Linux picasso 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux`)
```
absl-py                      2.1.0
aiohttp                      3.9.3
aiosignal                    1.3.1
astunparse                   1.6.3
attrs                        23.2.0
cachetools                   5.3.2
certifi                      2024.2.2
charset-normalizer           3.3.2
coloredlogs                  15.0.1
datasets                     2.17.0
diffusers                    0.27.2
dill                         0.3.8
evaluate                     0.4.1
filelock                     3.13.1
flatbuffers                  23.5.26
frozenlist                   1.4.1
fsspec                       2023.10.0
gast                         0.5.4
google-auth                  2.27.0
google-auth-oauthlib         1.2.0
google-pasta                 0.2.0
grpcio                       1.60.1
h5py                         3.10.0
huggingface-hub              0.20.3
humanfriendly                10.0
idna                         3.6
importlib-metadata           7.0.1
Jinja2                       3.1.3
keras                        2.15.0
libclang                     16.0.6
Markdown                     3.5.2
markdown-it-py               3.0.0
MarkupSafe                   2.1.5
mdurl                        0.1.2
ml-dtypes                    0.2.0
mpmath                       1.3.0
multidict                    6.0.5
multiprocess                 0.70.16
networkx                     3.2.1
numpy                        1.26.4
nvidia-cublas-cu11           11.10.3.66
nvidia-cublas-cu12           12.1.3.1
nvidia-cuda-cupti-cu12       12.1.105
nvidia-cuda-nvrtc-cu11       11.7.99
nvidia-cuda-nvrtc-cu12       12.1.105
nvidia-cuda-runtime-cu11     11.7.99
nvidia-cuda-runtime-cu12     12.1.105
nvidia-cudnn-cu11            8.5.0.96
nvidia-cudnn-cu12            8.9.2.26
nvidia-cufft-cu12            11.0.2.54
nvidia-curand-cu12           10.3.2.106
nvidia-cusolver-cu12         11.4.5.107
nvidia-cusparse-cu12         12.1.0.106
nvidia-nccl-cu12             2.19.3
nvidia-nvjitlink-cu12        12.3.101
nvidia-nvtx-cu12             12.1.105
oauthlib                     3.2.2
onnx                         1.15.0
onnx-simplifier              0.4.35
onnxmltools                  1.12.0
onnxruntime                  1.17.0
onnxscript                   0.1.0.dev20240210
opt-einsum                   3.3.0
optimum                      1.16.2
packaging                    23.2
pandas                       2.2.0
pillow                       10.2.0
pip                          23.0.1
protobuf                     4.25.2
psutil                       5.9.8
pyarrow                      15.0.0
pyarrow-hotfix               0.6
pyasn1                       0.5.1
pyasn1-modules               0.3.0
Pygments                     2.17.2
python-dateutil              2.8.2
pytz                         2024.1
PyYAML                       6.0.1
regex                        2023.12.25
requests                     2.31.0
requests-oauthlib            1.3.1
responses                    0.18.0
rich                         13.7.0
rsa                          4.9
safetensors                  0.4.2
sentencepiece                0.1.99
setuptools                   66.1.1
six                          1.16.0
sympy                        1.12
tensorboard                  2.15.2
tensorboard-data-server      0.7.2
tensorflow                   2.15.0.post1
tensorflow-estimator         2.15.0
tensorflow-io-gcs-filesystem 0.36.0
termcolor                    2.4.0
timm                         0.9.12
tokenizers                   0.15.1
torch                        2.2.0
torchvision                  0.17.0
tqdm                         4.66.2
transformers                 4.37.2
triton                       2.2.0
typing_extensions            4.9.0
tzdata                       2023.4
urllib3                      2.2.0
Werkzeug                     3.0.1
wheel                        0.42.0
wrapt                        1.14.1
xxhash                       3.4.1
yarl                         1.9.4
zipp                         3.17.0
```

**Comment by vitoplantamura** [comment]
thanks for the detailed information.

The problem is in the text_encoder. The UNET model works fine.
Specifically, the problem is that the
convert_stable_diffusion_checkpoint_to_onnx.py script produces a
text_encoder with two outputs: ["last_hidden_state", "pooler_output"],
while the OnnxStream SD application expects only one (i.e.
"last_hidden_state").

To make your model work, I simply deleted the last 3 lines in the model.txt
file of the text_encoder, in the text_encoder_fp32 directory; this also
includes the Flatten operator, which therefore no longer needs to be
converted to a Squeeze.

Probably a more correct solution is to modify the
convert_stable_diffusion_checkpoint_to_onnx.py script to generate an ONNX
file with only one output, i.e. "last_hidden_state", eliminating the
unnecessary output (i.e. "pooler_output").

Let me know if this solves the problem with other finetuned models too,

Vito

**Comment by thexa4** [comment]
Removing the last 3 lines of the text_encoder model.txt works with the finetuned model too, thanks for the help!

Rremoving the pooler_output from the export script doesn't seem to prevent the squeeze to be needed but the line removal workaround works.
