### ISSUE TITLE
vae_decoder_qu8/range_data.txt value generation

### ISSUE THREAD

**Issue by thexa4** [vitoplantamura/OnnxStream#63]
I'm trying to convert a checkpoint to run with OnnxStream but I can't seem to figure out how to generate the `range_data.txt` file.

Are there default values that you should fill in before running with `--decoder-calibrate`? If the file doesn't exist the application quits before running the calibration.

**Comment by vitoplantamura** [comment]
hi,

an empty file should be sufficient for the first run.

However, consider that you probably don't need to calibrate the VAE
decoder, for these reasons:

1) typically the SD 1.5 VAE decoder is common to all SD 1.5 derivations.
Typically finetune only alters the UNET model.

2) the quantized version of the VAE decoder is only needed to keep RAM
usage under 300MB, and is only used when the "--rpi-lowmem" option is
specified.

Vito
