### ISSUE TITLE
(LLM) Less: unexpected shape of output

### ISSUE THREAD

**Issue by cheapie** [vitoplantamura/OnnxStream#73]
The LLM example builds fine, but attempting to run it results in the following output:
```
$ ./llm 
Model: TinyLlama-1.1B-Chat-v0.3-fp16
Loading weights...=== ERROR === Less: unexpected shape of output.
```
I have observed this on both amd64 (AMD Ryzen 7 2700X and Intel Atom x5-Z8350) and riscv64 (StarFive JH7110) so far, so I don't believe it's any sort of instruction set issue. With MAX_SPEED disabled, the output is the same but it takes longer to fail.

The issue appears to have been introduced by commit 8a07664.

**Comment by vitoplantamura** [comment]
You are right! Just fixed!

Could you try again?

Thank you, Vito

**Comment by cheapie** [comment]
Yep, seems to work fine now. Thanks!
