### ISSUE TITLE
(Not an issue) WASM Branch: How to build?

### ISSUE THREAD

**Issue by JVGA8837** [vitoplantamura/OnnxStream#84]
I've noticed there's a new wasm branch in the repo, is there a way to build and test it yet or is it still too early in development to test?

**Comment by vitoplantamura** [comment]
hi @JVGA8837,

you can easily build it with Bazel, however within a week I plan to finish
the development and merge that branch into master. I developed a very nice
demo with yolov8n, which I haven't committed yet, to demonstrate the use
and performance of OnnxStream for wasm!

Vito

**Comment by JVGA8837** [comment]
That sounds great, i'll be sure to check it out when it's finished!
