### ISSUE TITLE
Runtime error : fatal error in worker thread: "read_file: invalid size of file."

### ISSUE THREAD

**Issue by har-in-air** [vitoplantamura/OnnxStream#9]
Hi, my platform is Ubuntu 22.04, AMD Ryzen 5 2500U with 12GB RAM, about 6.5GB available as per "free -h"
Built without issues.  Extracted the weights archive to compiled executable directory. 
Getting a run time error
``
./sd --models-path  ./SD/ --steps 3 
``

----------------[start]------------------
positive_prompt: a photo of an astronaut riding a horse on mars
negative_prompt: ugly, blurry
output_png_path: ./result.png
steps: 3
----------------[prompt]------------------
=== ERROR === DiskPrefetchWeightsProvider::provide: fatal error in worker thread: "read_file: invalid size of file."

I also tried "--rpi" based on your solution for another issue, but I get the same error.

**Comment by har-in-air** [comment]
Sorry, it was an issue with extracting the weights archive. I installed and used "unrar" and that worked.

**Comment by theskyblockman** [comment]
Hello, could someone tell me which archive was not extracted properly, by running ``./sd --xl --models-path stable-diffusion-xl-base-1.0-onnxstream/ --rpi`` I get the same error as above

**Comment by theskyblockman** [comment]
I've figured it, you **must** install LFS before cloning the repo
